# Generated by Django 3.1.3 on 2020-12-11 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('cheffPic', models.URLField()),
                ('cheffName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fPic', models.URLField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.menu')),
            ],
        ),
    ]
